### ISSUE TITLE
Enhancement: Support for per-tenant branding in vCD 9.7

### ISSUE THREAD

**Issue by tschoergez** [jondwaite/vcd-h5-themes#5]
In vCD 9.7 it is now possible to publish themes on a per-tenant base. Would be a great addition to the module to support this.
For the Get|Set-Branding cmdlets an additional switch --tenant could be added, that calls the /branding/tenant/{org} endpoint to activate a theme or set the logo/color for a given org.

**Comment by jondwaite** [comment]
I agree, once I have my 9.7 lab fully updated will get this added.

**Comment by jondwaite** [comment]
Get-Branding and Set-Branding cmdlets now support a '-Tenant' switch in 9.7 environments (API v32.0) to allow customization on a per-tenant basis. v1.4.1 has also been pushed to PSGallery to enable this functionality. (Update-Module vcd-h5-themes).
