### ISSUE TITLE
Set-Branding -portalColor does not work

### ISSUE THREAD

**Issue by ussrfish** [jondwaite/vcd-h5-themes#7]
I am unable to configure any portalColor with Set-Branding.  It fails to set any value.  No error is generated.  I've tried the syntax in several different ways with the same result.  We're testing against vCD 9.7.0.2. 

PS C:\Users\lab_rfish\Downloads> set-branding -server $server -portalName "testvCloud" -portalColor "#0F2D61"
Branding configuration sent successfully.
PS C:\Users\lab_rfish\Downloads> Get-Branding | fl

portalName    : testvCloud
portalColor   :
selectedTheme : @{themeType=BUILT_IN; name=Default}

**Comment by jondwaite** [comment]
Yup, reproduced this here - not sure what broke but will take a look and try and fix. Thanks for the report.

**Comment by jondwaite** [comment]
Fixed now - accidental use of '=' instead of '-eq' in a string comparison. Will push an update to PSGallery soon, but if you refresh vcd-h5-themes.psm1 from github should all now be working for you.
